<?php
require 'vendor/autoload.php';
use App\Models\School;
use App\Models\Department;
use App\Models\Programme;
use Illuminate\Support\Str;

$data = [
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'COMMUNITY HEALTH STUDIES (CHS)', 'COMMUNITY HEALTH', 4],
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'COMMUNITY HEALTH STUDIES (CHS)', 'FAMILY HEALTH', 4],
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'COMMUNITY HEALTH STUDIES (CHS)', 'HEALTH EDUCATION AND PROMOTION', 4],
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'MEDICAL EMERGENCY STUDIES (MES)', 'PARAMEDICINE SCIENCE', 4],
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'MEDICAL EMERGENCY STUDIES (MES)', 'ORTHOPEDIC PLASTER CAST', 4],
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'DENTAL HEALTH STUDIES (DHS)', 'DENTAL THERAPY', 4],
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'DENTAL HEALTH STUDIES (DHS)', 'DENTAL SURGERY TECHNOLOGY', 4],
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'MEDICAL DIAGNOSTIC STUDIES (MDS)', 'MEDICAL LABORATORY TECHNOLOGY', 4],
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'MEDICAL DIAGNOSTIC STUDIES (MDS)', 'MEDICAL IMAGING TECHNOLOGY', 4],
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'MEDICAL THERAPY AND INTERVENTION SCIENCES', 'PHARMACY', 4],
    ['SCHOOL OF CLINICAL TECHNOLOGY', 'MEDICAL THERAPY AND INTERVENTION SCIENCES', 'DISPENSING OPTICIANRY', 4],
    ['SCHOOL OF ALLIED HEALTH SCIENCES', 'PUBLIC HEALTH STUDIES (PHS)', 'ENVIRONMENTAL HEALTH TECHNOLOGY', 4],
    ['SCHOOL OF ALLIED HEALTH SCIENCES', 'PUBLIC HEALTH STUDIES (PHS)', 'PUBLIC HEALTH TECHNOLOGY', 4],
    ['SCHOOL OF ALLIED HEALTH SCIENCES', 'CARE STUDIES', 'NUTRITION AND DIETETICS', 4],
    ['SCHOOL OF ALLIED HEALTH SCIENCES', 'CARE STUDIES', 'SOCIAL WORK', 4],
    ['SCHOOL OF ALLIED HEALTH SCIENCES', 'HEALTH INFORMATION MANAGEMENT', 'HEALTH INFORMATION MANAGEMENT', 4],
    ['SCHOOL OF ALLIED HEALTH SCIENCES', 'MEDICAL STORE MANAGEMENT', 'MEDICAL STORE MANAGEMENT', 4],
    ['SCHOOL OF ALLIED HEALTH SCIENCES', 'APPLIED SCIENCES', 'REMEDIAL STUDIES', 4],
    ['SCHOOL OF FINANCE, BUSSINESS AND MANAGEMENT STUDIES', 'BUSSINESS ADMINISTRATION AND MANAGEMENT', 'ACCOUNTANCY', 4],
    ['SCHOOL OF PURE AND APPLIED SCIENCES', 'COMPUTER STUDIES', 'COMPUTER SCIENCE', 4],
    ['SCHOOL OF PURE AND APPLIED SCIENCES', 'COMPUTER STUDIES', 'CYBER SECURITY AND DATA PROTECTION', 4],
    ['SCHOOL OF PURE AND APPLIED SCIENCES', 'COMPUTER STUDIES', 'ARTIFICIAL INTELLIGENCE', 4],
    ['SCHOOL OF PURE AND APPLIED SCIENCES', 'COMPUTER STUDIES', 'SOFTWARE AND WEB DEVELOPMENT', 4],
    ['SCHOOL OF ERNGINEERING', 'ENGINEERING STUDIES', 'ELECTRICAL \ELECTRONICS ENGINEERING', 4],
    ['SCHOOL OF ERNGINEERING', 'ENGINEERING STUDIES', 'BIOMEDICAL ENGINEERING', 4],
    ['SCHOOL OF ERNGINEERING', 'ENGINEERING STUDIES', 'COMPUTER ENGINNEERING', 4],
];

foreach ($data as $row) {
    $schoolName = $row[0];
    $school = School::firstOrCreate(
        ['name' => $schoolName],
        [
            'slug' => Str::slug($schoolName),
            'code' => strtoupper(substr(str_replace(' ', '', $schoolName), 0, 5)) . rand(10, 99)
        ]
    );
    
    $deptName = $row[1];
    $dept = Department::firstOrCreate(
        ['name' => $deptName, 'school_id' => $school->id],
        [
            'slug' => Str::slug($deptName),
            'code' => strtoupper(substr(str_replace(' ', '', $deptName), 0, 5)) . rand(10, 99)
        ]
    );
    
    Programme::updateOrCreate(
        ['name' => $row[2], 'department_id' => $dept->id],
        ['duration_years' => $row[3]]
    );
}
echo "Import completed successfully!";
